ATG2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path,include
from blog import views
from django.conf.urls import url
from django.contrib.auth.views import LoginView,LogoutView
urlpatterns = [
    path('',views.home),
    path('register/',views.register),
    path('login/',LoginView.as_view(template_name='login.html')),
    path('logout/',LogoutView.as_view(template_name='logout.html')),
    path('dashboard/',views.dashboard),
    path('newarticle/',views.newarticle),
    path('delete/<int:id>',views.deletearticle,name="deletearticle"),
    url(r'^captcha/', include('captcha.urls')),
    path('otherarticle/<str:search>',views.otherarticle),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
class Article(models.Model):
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	articledate=models.DateField()
	title=models.CharField(max_length=1000)
	Description=models.CharField(max_length=10000)
	Image=models.ImageField(upload_to="article_image",blank=False)
	Public=models.BooleanField(default=False)
	def __str__(self):
		return self.title
# Create your models here.

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Article
from captcha.fields import CaptchaField
class UserRegistrationForm(UserCreationForm):
	email=forms.EmailField()
	captcha=CaptchaField()
	class Meta:
		model=User
		fields=['username','email','password1','password2']
class ArticleForm(forms.ModelForm):
	class Meta():
		model=Article
		fields=['title','Description',"Image","Public"]

blog/views.py
from django.shortcuts import render,redirect
from .models import Article
from .forms import UserRegistrationForm,ArticleForm
from django.contrib import messages
from datetime import date
from django.contrib.auth.models import User
def home(request):
	user=request.GET.get("q")
	cont=0
	if user:
		try:
			User.objects.get(username=user)
			cont=1
		except:
			cont=2
	return render(request,"index.html",{"cont":cont,'search':user})
def register(request):
	if request.method=="POST":
		form=UserRegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			reg_user=form.cleaned_data.get('username')
			messages.success(request,"Hello %s, You Have Successfully registered"%reg_user)
			return redirect('/blog/login')
	else:
		form=UserRegistrationForm()
	
	return render(request,"register.html",{"form":form})
def dashboard(request):
	return render(request,"dashboard.html")
def newarticle(request):
	if request.method=="POST":
		form=ArticleForm(request.POST,request.FILES)
		if form.is_valid():
			form1=form.save(commit=False)
			form1.user=request.user
			form1.articledate=date.today()
			form1.save()
			messages.success(request,"You Aritcle Has Been Posted Successfully")
			return redirect('/blog/dashboard')
	else:
		form=ArticleForm()
	return render(request,"newarticle.html",{'form':form})
def deletearticle(request,id):
	a=Article.objects.get(pk=id)
	a.delete()
	messages.success(request,"Article Has Been Successfully Deleted!")
	return redirect('/blog/dashboard')
def otherarticle(request,search):
	search=User.objects.get(username=search)
	return render(request,'otherarticle.html',{'search':search})
			# Create your views here.

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
  <style>
    {% block style %}
    {% endblock %}
    </style>
    
  </head>
  <body>
    {% block body %}
{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/dashboard.html
{% extends 'base.html'%}
{% block body%}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Hello, {{user}}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/blog">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <a href="/blog/newarticle" class="btn btn-outline-success my-2 my-sm-0 mr-3">New Article</a>
      <a href="/blog/logout" class="btn btn-outline-danger my-2 my-sm-0">Logout</a>
    </div>
  </div>
</nav>
{% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
 {{ message }}
</div>
{% endfor %}
{% endif %}
<ol>
<div>
	{% if user.article_set.all %}
	{% for article in user.article_set.all %}
  <div class="card mt-3" style="width: 18rem;">
  <img src="/media/{{article.Image}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text">{{article.Description}}</p>
    <h6 class="card-subtitle mb-2 text-muted">Published : {{article.articledate}}</h6>
    <a href="/blog/delete/{{article.id}}" class="card-link btn btn-outline-danger mt-2">Delete</a>
  </div>
</div>
{% endfor %}
{% else %}

<h2 class="text-muted mt-5">No Article Posted Yet.</h2>
{% endif %}
</div>
</ol>
{% endblock %}
</html>

templates/index.html
{% extends 'base.html' %}
{% block body %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">{% if user.is_authenticated %}Hello {{user}}{% else %}Hello{% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/blog">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      {% if user.is_authenticated %}
      <a href="/blog/dashboard" class="btn btn-outline-primary my-2 my-sm-0 mr-3">Dashboard</a>
      <a href="/blog/logout" class="btn btn-outline-danger my-2 my-sm-0">Logout</a>
      {% else %}
      <a href="/blog/login" class="btn btn-outline-primary my-2 my-sm-0 mr-3">Login</a>
      <a href="/blog/register" class="btn btn-outline-primary my-2 my-sm-0">Register</a>
      
    	{% endif %}
    </div>
  </div>
</nav>
<form class="form-inline" method="GET" action="">
    <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search"></input></br>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
{% if cont == 1 %} 
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{ search }}</h5>
    <a href="/blog/otherarticle/{{search}}" class="card-link">Show Articles</a>
  </div>
</div>
{% endif %}
{% if cont == 2 %}
<h5 class="card-title">Sorry no Result Found</h5>
{% endif %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block body %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Hello</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/blog">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <a href="/blog/register" class="btn btn-outline-primary my-2 my-sm-0">Register</a>
     
    </div>
  </div>
</nav>
{% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
 {{ message }}
</div>
{% endfor %}
{% endif %}
<div>
<form method="POST">{% csrf_token %}
	<p>{{form.as_p}}</p>
	<button type="submit" class="btn btn-primary ml-23%">Login</button>
</form></div>
{% endblock %}

templates/logout.html
{% extends 'base.html' %}

{% block body %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Hello</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/blog">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <a href="/blog/login" class="btn btn-outline-primary my-2 my-sm-0">Login Again</a>
     
    </div>
  </div>
</nav>
<h2>You Have been Successfully Logout</h2>
{% endblock %}

templates/newarticle.html
{% extends 'base.html' %}

{% block body %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Hello, {{user}}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/blog">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <a href="/blog/logout" class="btn btn-outline-danger my-2 my-sm-0">Logout</a>
    </div>
  </div>
</nav>
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
{{ form.as_p }}
<button type="Submit" class="btn btn-primary">POST</button>
<a href="/blog/dashboard" class="btn btn-outline-danger">Discard</a>
</form>{% endblock %}

templates/otherarticle.html
{% extends 'base.html'%}
{% block body%}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Hello</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/blog">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <a href="/blog/logout" class="btn btn-outline-danger my-2 my-sm-0">Logout</a>
    </div>
  </div>
</nav>
<ol>
<div>
	{{ search }}
  {% if search.article_set.all %}
	{% for article in search.article_set.all %}
  {% if article.Public is True %}
  <div class="card mt-3" style="width: 18rem;">
  <img src="/media/{{article.Image}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{article.title}}</h5>
    <p class="card-text">{{article.Description}}</p>
    <h6 class="card-subtitle mb-2 text-muted">Published : {{article.articledate}}</h6>
    </div>
</div>
{% endif %}
{% endfor %}
{% else %}

<h2 class="text-muted mt-5">No Article Posted Yet.</h2>
{% endif %}
</div>
</ol>
{% endblock %}
</html>

templates/register.html
{% extends 'base.html' %}
{% block body %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Hello</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/blog">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="form-inline my-2 my-lg-0">
      <a href="/blog/login" class="btn btn-outline-primary my-2 my-sm-0">Login</a>
    </div>
  </div>
</nav></br></br>
<form method="POST">{% csrf_token %}
{{ form.as_p }}
<button type="Submit" class="btn btn-primary">Register</button>
</form>
{% endblock %}